날씨 예측에 필요한 라이브러리

In [1]:
import pandas as pd # 데이터 다루기 + 데이터셋 불러오기

import tensorflow as tf # 날씨 예측 인공지능 구현하기 위한 라이브러리

import numpy as np # 데이터 추가적으로 다루기 위한 라이브러리

데이터 셋 불러오기

In [2]:
df = pd.read_csv(r'Dataset.csv',encoding='cp949') # 데이터 셋 불러오기

데이터 내용 확인

In [3]:
df

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),최대 풍속 풍향(16방위),평균 풍속(m/s),...,최소 상대습도 시각(hhmi),평균 상대습도(%),평균 증기압(hPa),최고 해면기압(hPa),최저 해면기압(hPa),평균 해면기압(hPa),평균 전운량(1/10),평균 중하층운량(1/10),평균 지면온도(°C),최저 초상온도(°C)
0,102,백령도,2022-02-28,5.3,0.5,8.4,NaN,6.9,160,3.8,...,1423,86.9,7.7,1021.4,1014.5,1018.4,6.0,3.6,8.0,-7.2
1,102,백령도,2022-03-01,3.8,2.6,6.6,NaN,11.7,340,6.8,...,1646,62.6,5.1,1018.5,1012.4,1015.8,3.6,3.6,6.2,1.0
2,102,백령도,2022-03-02,5.4,2.0,8.6,NaN,8.7,250,5.1,...,1444,55.4,4.9,1018.3,1014.2,1016.3,0.0,0.0,8.7,-2.1
3,102,백령도,2022-03-03,5.1,1.9,8.9,NaN,5.6,160,2.7,...,1207,55.3,4.7,1018.8,1015.1,1016.9,0.0,0.0,10.3,-2.8
4,102,백령도,2022-03-04,6.5,4.2,11.0,NaN,10.9,340,6.8,...,1645,81.3,7.8,1015.2,1003.7,1009.0,7.8,4.8,9.1,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,201,강화,2022-08-24,23.1,19.2,27.8,NaN,3.2,70,1.3,...,843,76.0,21.3,1010.6,1007.4,1008.7,7.4,3.9,24.6,18.0
542,201,강화,2022-08-25,21.5,19.4,24.0,0.7,4.3,320,1.7,...,1339,86.8,22.2,1009.4,1007.4,1008.5,8.4,5.0,23.5,19.1
543,201,강화,2022-08-26,22.7,18.3,26.6,NaN,4.4,250,2.0,...,1218,85.5,23.3,1009.3,1006.3,1008.0,5.3,1.8,25.6,17.5
544,201,강화,2022-08-27,NaN,NaN,NaN,0.2,4.4,270,2.1,...,1329,59.5,14.7,1014.4,1007.9,1011.6,1.4,0.3,NaN,NaN
545,201,강화,2022-08-28,20.2,13.0,27.0,NaN,3.0,250,1.1,...,1522,69.4,15.9,1017.4,1014.3,1015.7,4.1,0.6,23.7,11.4

데이터 전처리 - 불필요한 데이터 제거

In [4]:
df = df.drop(columns=['지점'])

데이터 columns 확인 (불필요한 데이터 요소 제거가 되었는지 확인용)

In [5]:
df.columns

Index(['지점명', '일시', '평균기온(°C)', '최저기온(°C)', '최고기온(°C)', '일강수량(mm)',
       '최대 풍속(m/s)', '최대 풍속 풍향(16방위)', '평균 풍속(m/s)', '최다풍향(16방위)',
       '최소 상대습도(%)', '최소 상대습도 시각(hhmi)', '평균 상대습도(%)', '평균 증기압(hPa)',
       '최고 해면기압(hPa)', '최저 해면기압(hPa)', '평균 해면기압(hPa)', '평균 전운량(1/10)',
       '평균 중하층운량(1/10)', '평균 지면온도(°C)', '최저 초상온도(°C)'],
      dtype='object')

In [6]:
y = df.drop(columns=['지점명','일시'])

In [7]:
y = y.fillna(0)

In [8]:
y

,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),최대 풍속 풍향(16방위),평균 풍속(m/s),최다풍향(16방위),최소 상대습도(%),최소 상대습도 시각(hhmi),평균 상대습도(%),평균 증기압(hPa),최고 해면기압(hPa),최저 해면기압(hPa),평균 해면기압(hPa),평균 전운량(1/10),평균 중하층운량(1/10),평균 지면온도(°C),최저 초상온도(°C)
0,5.3,0.5,8.4,0.0,6.9,160,3.8,160,76,1423,86.9,7.7,1021.4,1014.5,1018.4,6.0,3.6,8.0,-7.2
1,3.8,2.6,6.6,0.0,11.7,340,6.8,320,35,1646,62.6,5.1,1018.5,1012.4,1015.8,3.6,3.6,6.2,1.0
2,5.4,2.0,8.6,0.0,8.7,250,5.1,250,33,1444,55.4,4.9,1018.3,1014.2,1016.3,0.0,0.0,8.7,-2.1
3,5.1,1.9,8.9,0.0,5.6,160,2.7,160,20,1207,55.3,4.7,1018.8,1015.1,1016.9,0.0,0.0,10.3,-2.8
4,6.5,4.2,11.0,0.0,10.9,340,6.8,140,50,1645,81.3,7.8,1015.2,1003.7,1009.0,7.8,4.8,9.1,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,23.1,19.2,27.8,0.0,3.2,70,1.3,70,57,843,76.0,21.3,1010.6,1007.4,1008.7,7.4,3.9,24.6,18.0
542,21.5,19.4,24.0,0.7,4.3,320,1.7,290,74,1339,86.8,22.2,1009.4,1007.4,1008.5,8.4,5.0,23.5,19.1
543,22.7,18.3,26.6,0.0,4.4,250,2.0,290,62,1218,85.5,23.3,1009.3,1006.3,1008.0,5.3,1.8,25.6,17.5
544,0.0,0.0,0.0,0.2,4.4,270,2.1,270,45,1329,59.5,14.7,1014.4,1007.9,1011.6,1.4,0.3,0.0,0.0
545,20.2,13.0,27.0,0.0,3.0,250,1.1,140,38,1522,69.4,15.9,1017.4,1014.3,1015.7,4.1,0.6,23.7,11.4

정규화 처리(모든 데이터 -1 ~ 1사이 범위로 변경)

In [9]:
y_mean = y.mean().to_numpy()
y_std = y.std().to_numpy()
y = (y-y.mean())/y.std()

정규화 처리 후 데이터 확인

In [10]:
y

,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),최대 풍속 풍향(16방위),평균 풍속(m/s),최다풍향(16방위),최소 상대습도(%),최소 상대습도 시각(hhmi),평균 상대습도(%),평균 증기압(hPa),최고 해면기압(hPa),최저 해면기압(hPa),평균 해면기압(hPa),평균 전운량(1/10),평균 중하층운량(1/10),평균 지면온도(°C),최저 초상온도(°C)
0,-1.582330,-1.648783,-1.717753,-0.253786,0.473534,-0.962796,0.666772,-0.688323,1.022607,0.239872,0.727200,-1.017361,1.165391,0.829056,1.080565,0.118680,-0.011747,-1.546935,-1.956089
1,-1.783106,-1.387557,-1.963328,-0.253786,2.808945,1.505860,2.987582,1.293612,-1.024802,0.699446,-0.853640,-1.308740,0.751373,0.530521,0.706270,-0.691733,-0.011747,-1.764912,-1.082266
2,-1.568945,-1.462193,-1.690467,-0.253786,1.349313,0.271532,1.672457,0.426515,-1.124675,0.283150,-1.322038,-1.331153,0.722820,0.786408,0.778250,-1.907352,-1.259875,-1.462166,-1.412614
3,-1.609100,-1.474632,-1.649538,-0.253786,-0.158973,-0.962796,-0.184191,-0.688323,-1.773854,-0.205275,-1.328543,-1.353567,0.794202,0.914351,0.864626,-1.907352,-1.259875,-1.268408,-1.487209
4,-1.421709,-1.188527,-1.363033,-0.253786,2.419709,1.505860,2.987582,-0.936065,-0.275750,0.697385,0.362891,-1.006154,0.280248,-0.706267,-0.272653,0.726490,0.404295,-1.413726,-0.965046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,0.800211,0.677375,0.929003,-0.253786,-1.326679,-2.197125,-1.267236,-1.803162,0.073808,-0.955431,0.018099,0.506772,-0.376471,-0.180277,-0.315840,0.591421,0.092263,0.463302,0.729318
542,0.586050,0.702254,0.410567,-0.221391,-0.791480,1.231565,-0.957795,0.921999,0.922733,0.066759,0.720694,0.607633,-0.547789,-0.180277,-0.344632,0.929093,0.473636,0.330093,0.846538
543,0.746671,0.565421,0.765287,-0.253786,-0.742826,0.271532,-0.725714,0.921999,0.323492,-0.182606,0.636123,0.730909,-0.562065,-0.336652,-0.416612,-0.117690,-0.635811,0.584401,0.676036
544,-2.291738,-1.710980,-2.863771,-0.244531,-0.742826,0.545827,-0.648353,0.674257,-0.525434,0.046151,-1.055311,-0.232881,0.166036,-0.109197,0.101642,-1.434611,-1.155864,-2.515723,-1.188830
545,0.412044,-0.093865,0.819859,-0.253786,-1.423988,0.271532,-1.421957,-0.936065,-0.874991,0.443898,-0.411265,-0.098399,0.594331,0.800624,0.691875,-0.522897,-1.051853,0.354313,0.025997

학습할 데이터 제작

In [25]:
from IPython.display import Image
  
# 이미지 넣기
Image(url="weatherAL.png")

In [11]:
trainY = []
trainX = []
for i in range(y.shape[0]-3):
    trainX.append(y[i:i+3].to_numpy())
    trainY.append(y[i+3:i+4].to_numpy())

trainX = np.array(trainX)
trainY = np.array(trainY)

인공지능 학습할 수 있게 데이터 구조 변경

In [14]:
trainY = trainY.reshape((-1,19))

In [15]:
trainX

array([[[-1.58232983, -1.64878301, -1.71775304, ..., -0.01174723,
         -1.54693471, -1.95608913],
        [-1.78310573, -1.38755673, -1.96332838, ..., -0.01174723,
         -1.76491218, -1.08226627],
        [-1.56894477, -1.46219281, -1.69046689, ..., -1.25987454,
         -1.46216569, -1.41261394]],

       [[-1.78310573, -1.38755673, -1.96332838, ..., -0.01174723,
         -1.76491218, -1.08226627],
        [-1.56894477, -1.46219281, -1.69046689, ..., -1.25987454,
         -1.46216569, -1.41261394],
        [-1.60909995, -1.47463215, -1.64953767, ..., -1.25987454,
         -1.26840795, -1.48720857]],

       [[-1.56894477, -1.46219281, -1.69046689, ..., -1.25987454,
         -1.46216569, -1.41261394],
        [-1.60909995, -1.47463215, -1.64953767, ..., -1.25987454,
         -1.26840795, -1.48720857],
        [-1.42170911, -1.18852718, -1.3630331 , ...,  0.40429521,
         -1.41372626, -0.96504613]],

       ...,

       [[ 0.89390628,  0.86396503,  0.91536035, ..., -0.39311946,
          0.66916953,  0.80391235],
        [ 0.80021086,  0.67737483,  0.92900342, ...,  0.09226338,
          0.46330192,  0.72931771],
        [ 0.5860499 ,  0.70225352,  0.41056659, ...,  0.47363561,
          0.33009347,  0.84653785]],

       [[ 0.80021086,  0.67737483,  0.92900342, ...,  0.09226338,
          0.46330192,  0.72931771],
        [ 0.5860499 ,  0.70225352,  0.41056659, ...,  0.47363561,
          0.33009347,  0.84653785],
        [ 0.74667062,  0.56542071,  0.76528653, ..., -0.63581088,
          0.58440051,  0.67603583]],

       [[ 0.5860499 ,  0.70225352,  0.41056659, ...,  0.47363561,
          0.33009347,  0.84653785],
        [ 0.74667062,  0.56542071,  0.76528653, ..., -0.63581088,
          0.58440051,  0.67603583],
        [-2.29173801, -1.71097974, -2.8637713 , ..., -1.15586393,
         -2.51572345, -1.18883003]]])

인공지능 모델 구현(LSTM 이용한 날씨 예측)

In [16]:
model = tf.keras.Sequential()

model.add(tf.keras.layers.LSTM(256,activation='tanh',input_shape=(3,19),return_sequences=True))
model.add(tf.keras.layers.LSTM(128,activation='tanh'))
model.add(tf.keras.layers.Dense(19,activation='tanh'))

모델 구조 확인용

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm (LSTM)                 (None, 3, 256)            282624

 lstm_1 (LSTM)               (None, 128)               197120

 dense (Dense)               (None, 19)                2451

=================================================================
Total params: 482,195
Trainable params: 482,195
Non-trainable params: 0
_________________________________________________________________

학습방법 설정

In [18]:
model.compile(loss='mse',optimizer='adam') # loss='mse' 사용한 이유 : 회귀 문제이기 때문에

인공지능 학습 실행

In [19]:
model.fit(trainX,trainY,epochs=50)

Epoch 1/50
17/17 [==============================] - 3s 9ms/step - loss: 0.7577
Epoch 2/50
17/17 [==============================] - 0s 10ms/step - loss: 0.5998
Epoch 3/50
17/17 [==============================] - 0s 12ms/step - loss: 0.5657
Epoch 4/50
17/17 [==============================] - 0s 10ms/step - loss: 0.5438
Epoch 5/50
17/17 [==============================] - 0s 10ms/step - loss: 0.5281
Epoch 6/50
17/17 [==============================] - 0s 10ms/step - loss: 0.5141
Epoch 7/50
17/17 [==============================] - 0s 9ms/step - loss: 0.4981
Epoch 8/50
17/17 [==============================] - 0s 10ms/step - loss: 0.4844
Epoch 9/50
17/17 [==============================] - 0s 10ms/step - loss: 0.4726
Epoch 10/50
17/17 [==============================] - 0s 9ms/step - loss: 0.4609
Epoch 11/50
17/17 [==============================] - 0s 9ms/step - loss: 0.4531
Epoch 12/50
17/17 [==============================] - 0s 9ms/step - loss: 0.4479
Epoch 13/50
17/17 [==============================] - 0s 10ms/step - loss: 0.4444
Epoch 14/50
17/17 [==============================] - 0s 10ms/step - loss: 0.4313
Epoch 15/50
17/17 [==============================] - 0s 11ms/step - loss: 0.4197
Epoch 16/50
17/17 [==============================] - 0s 11ms/step - loss: 0.4159
Epoch 17/50
17/17 [==============================] - 0s 10ms/step - loss: 0.4077
Epoch 18/50
17/17 [==============================] - 0s 10ms/step - loss: 0.3995
Epoch 19/50
17/17 [==============================] - 0s 10ms/step - loss: 0.3913
Epoch 20/50
17/17 [==============================] - 0s 11ms/step - loss: 0.3834
Epoch 21/50
17/17 [==============================] - 0s 11ms/step - loss: 0.3731
Epoch 22/50
17/17 [==============================] - 0s 12ms/step - loss: 0.3675
Epoch 23/50
17/17 [==============================] - 0s 11ms/step - loss: 0.3600
Epoch 24/50
17/17 [==============================] - 0s 10ms/step - loss: 0.3510
Epoch 25/50
17/17 [==============================] - 0s 10ms/step - loss: 0.3434
Epoch 26/50
17/17 [==============================] - 0s 10ms/step - loss: 0.3367
Epoch 27/50
17/17 [==============================] - 0s 10ms/step - loss: 0.3295
Epoch 28/50
17/17 [==============================] - 0s 10ms/step - loss: 0.3230
Epoch 29/50
17/17 [==============================] - 0s 10ms/step - loss: 0.3133
Epoch 30/50
17/17 [==============================] - 0s 11ms/step - loss: 0.3081
Epoch 31/50
17/17 [==============================] - 0s 10ms/step - loss: 0.3054
Epoch 32/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2969
Epoch 33/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2869
Epoch 34/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2796
Epoch 35/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2740
Epoch 36/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2663
Epoch 37/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2593
Epoch 38/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2543
Epoch 39/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2497
Epoch 40/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2469
Epoch 41/50
17/17 [==============================] - 0s 9ms/step - loss: 0.2387
Epoch 42/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2358
Epoch 43/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2311
Epoch 44/50
17/17 [==============================] - 0s 11ms/step - loss: 0.2265
Epoch 45/50
17/17 [==============================] - 0s 11ms/step - loss: 0.2238
Epoch 46/50
17/17 [==============================] - 0s 11ms/step - loss: 0.2214
Epoch 47/50
17/17 [==============================] - 0s 11ms/step - loss: 0.2186
Epoch 48/50
17/17 [==============================] - 0s 11ms/step - loss: 0.2142
Epoch 49/50
17/17 [==============================] - 0s 11ms/step - loss: 0.2103
Epoch 50/50
17/17 [==============================] - 0s 10ms/step - loss: 0.2085

다음날 예측할 데이터 출력

In [20]:
trainX[-1]

array([[ 0.5860499 ,  0.70225352,  0.41056659, -0.22139129, -0.79148042,
         1.23156529, -0.95779454,  0.92199918,  0.92273311,  0.0667593 ,
         0.7206944 ,  0.60763346, -0.54778868, -0.18027701, -0.34463215,
         0.92909272,  0.47363561,  0.33009347,  0.84653785],
       [ 0.74667062,  0.56542071,  0.76528653, -0.2537863 , -0.74282603,
         0.27153214, -0.72571356,  0.92199918,  0.32349162, -0.18260576,
         0.63612269,  0.73090891, -0.56206518, -0.33665248, -0.41661178,
        -0.11769044, -0.63581088,  0.58440051,  0.67603583],
       [-2.29173801, -1.71097974, -2.8637713 , -0.24453058, -0.74282603,
         0.54582732, -0.64835323,  0.67425727, -0.52543381,  0.04615062,
        -1.05531145, -0.232881  ,  0.16603619, -0.10919725,  0.10164157,
        -1.43461118, -1.15586393, -2.51572345, -1.18883003]])

다음날 날씨 예측 후 DataFrame 생성

In [21]:
result = pd.DataFrame(model.predict(trainX[-1:]).reshape((-1,19)))
# *y_std+y_mean

In [22]:
result

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0.491247,-0.141428,0.684603,-0.257506,-0.905295,0.531076,-0.860736,-0.856231,-0.762492,0.469695,-0.376219,0.03817,0.602545,0.725969,0.742911,-0.555152,-0.855138,0.563136,0.067484

역정규화 처리(정상적인 숫자로 변환)

In [23]:
y_std

array([  7.47101616,   8.03900737,   7.32972613,  21.60826966,
         2.05531292,  72.91414882,   1.29265222,  80.7291768 ,
        20.02531592, 485.23236529,  15.37157096,   8.92310641,
         7.00451921,   7.03435156,   6.94640955,   2.96145384,
         2.88432116,   8.25773431,   9.38405294])

역정규화 한 후, 예측 한 내용 확인

In [24]:
print(y.columns)
result.columns = y.columns
result*y_std+y_mean

Index(['평균기온(°C)', '최저기온(°C)', '최고기온(°C)', '일강수량(mm)', '최대 풍속(m/s)',
       '최대 풍속 풍향(16방위)', '평균 풍속(m/s)', '최다풍향(16방위)', '최소 상대습도(%)',
       '최소 상대습도 시각(hhmi)', '평균 상대습도(%)', '평균 증기압(hPa)', '최고 해면기압(hPa)',
       '최저 해면기압(hPa)', '평균 해면기압(hPa)', '평균 전운량(1/10)', '평균 중하층운량(1/10)',
       '평균 지면온도(°C)', '최저 초상온도(°C)'],
      dtype='object')

,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),최대 풍속 풍향(16방위),평균 풍속(m/s),최다풍향(16방위),최소 상대습도(%),최소 상대습도 시각(hhmi),평균 상대습도(%),평균 증기압(hPa),최고 해면기압(hPa),최저 해면기압(hPa),평균 해면기압(hPa),평균 전운량(1/10),평균 중하층운량(1/10),평균 지면온도(°C),최저 초상온도(°C)
0,20.791724,12.617637,26.008611,-0.080373,4.066076,268.924451,1.825463,146.444958,40.252825,1534.51727,69.938722,17.118613,1017.457532,1013.774852,1016.054518,4.004478,1.167392,25.424406,11.789318